repos:
  - src: "git@github.com:ohmyzsh/ohmyzsh.git"
    dst: "git@github.com:infinihardy/ohmyzsh.git"
  - src: "git@github.com:pyenv/pyenv.git"
    dst: "git@github.com:infinihardy/pyenv.git"
  - src: "git@github.com:pyenv/pyenv-virtualenv.git"
    dst: "git@github.com:infinihardy/pyenv-virtualenv.git"
  - src: "git@github.com:pyenv/pyenv-virtualenv.git"
    dst: "git@github.com:infinihardy/pyenv-virtualenv.git"
  - src: "git@github.com:nvm-sh/nvm.git"
    dst: "git@github.com:infinihardy/nvm.git"
