repos:
  - src: "git@github.com:ohmyzsh/ohmyzsh.git"
    dst: "git@github.com:luohf-infinilabs/ohmyzsh.git"
  - src: "git@github.com:pyenv/pyenv.git"
    dst: "git@github.com:luohf-infinilabs/pyenv.git"
  - src: "git@github.com:pyenv/pyenv-virtualenv.git"
    dst: "git@github.com:luohf-infinilabs/pyenv-virtualenv.git"
